var lang = {};

lang['indonasia'] = {
        a1: "Menangkan hadiah dari Lazada!",
        a2: "Untuk berterima kasih kepada pelanggan kami atas kesetiaan mereka, kami menawarkan kesempatan untuk mendapatkan hadiah rahasia!",
        a3: "Temukan hadiah rahasia",
        a4: "Yang harus Anda lakukan adalah memilih kotak kado yang tepat ",
        a5: "Orang-orang menyukai",
        a6: "Apakah mungkin untuk bermain lagi? :)",
        a7: "Saya mendengarnya! IPhone saya baru saja datang lewat pos, meskipun saya sudah punya, saya akan menjualnya, terima kasih semuanya!",
        a8: "Saya memiliki iPhone saya hari ini. Terima kasih!",
        a9: "Semua hadiah kosong !!!",
        a10: "Satu menjualnya padaku, ya.!",
        a11: "Saya pikir itu lelucon, tapi iPhone 10 saya datang pagi ini. Namun, Anda harus mengikuti semua instruksi dengan hati - hati..",
        a12: "Saya tidak pernah memenangkan apa pun, tetapi saya beruntung hari ini! Terima kasih!",
        a13: "Aku tersesat:(",
        a14: "Saya telah melihat permainan ini tahun lalu, tetapi saya mengabaikannya karena saya pikir itu tidak masuk akal.Kali ini saya mencoba dan saya menang: )",
        a15: "Terima kasih banyak, ini luar biasa!!!",
        a16: "Cukup konfirmasi nomor Anda di halaman berikutnya;)",
        a17: "Apakah saya satu-satunya yang tersesat? :( :( :( :(",
        a18: "Baiklah terima kasih! Terima kasih!",
        a19: "Itu lelucon?",
        a20: "Anda beruntung!",
        a21: "Anda adalah salah satu dari 10 orang yang dipilih untuk berpartisipasi dalam lotere loyalitas kami! Anda bisa mendapatkan 1 hadiah dari 4! Pilih satu kotak.",
        a22: "Maaf, kotak ini kosong! Percobaan tersisa ",
        a23: "Voucher Lazada Anda seharga Rp500.000 telah dipesan selama lima (5) menit!",
        a24: "Anda akan diarahkan ke <b>aplikasi resmi Lazada</b>.",
        a25: "Silakan <b>instal</b> untuk mengklaim hadiah Anda.",
        montharray: ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"],
        a26: "Jawaban",
        a27: "Suka",
        a28: "beberapa menit yang lalu",
        a29: "sejam yang lalu"
    },
    lang['english'] = {
        a1: "Win a prize from Lazada!",
        a2: "To thank our customers for their loyalty, we offer the opportunity to get a secret gift!",
        a3: "Find a secret gift",
        a4: "All you have to do is choose the right gift box",
        a5: "People like it",
        a6: "Is it possible to play again? :)",
        a7: "I heard about it! My iPhone just came in the mail, even though I already have one I'm going to sell it, thanks everyone!",
        a8: "I have my iPhone today. Thank you!",
        a9: "All gifts are empty!!!",
        a10: "Thank you!",
        a11: "I thought it was a joke, but my iPhone 10 arrived this morning. However, you must follow all instructions carefully..",
        a12: "I never won anything, but I got lucky today! Thank you!",
        a13: "I'm lost :(",
        a14: "I've seen this game last year but I ignored it because I thought it didn't make any sense. This time I tried and I won : )",
        a15: "Thank you very much, this is amazing!!!",
        a16: "Just confirm your number on the next page ;)",
        a17: "Am I the only one who got lost? :( :( :( :(",
        a18: "Thank you! Thank you!",
        a19: "That's a joke?",
        a20: "You are lucky!",
        a21: "You are one of 10 people selected to participate in our loyalty lottery! You can get 1 prize out of 4! Just select a box.",
        a22: "Sorry, this box is empty! You have more attempts ",
        a23: "Your Lazada voucher for Rp500,000 has been reserved for five (5) minutes!",
        a24: "You will be redirected to the official Lazada app.",
        a25: "Please install it to claim your reward.",
        montharray: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        a26: "Answer",
        a27: "Like",
        a28: "minutes ago",
        a29: "hour(s) ago"
    },
    lang['malay'] = {
       a1: "Menangi hadiah daripada Lazada!",
           a2: "Untuk berterima kasih kepada pelanggan kami atas kesetiaan mereka, kami menawarkan peluang untuk mendapatkan hadiah rahsia!",
           a3: "Cari hadiah rahsia",
           a4: "Apa yang anda perlu lakukan ialah memilih kotak hadiah yang betul",
           a5: "Orang sukakannya",
           a6: "Adakah mungkin untuk bermain semula? :)",
           a7: "Saya mendengarnya! iPhone saya baru sahaja dihantar melalui mel, walaupun saya sudah mempunyai satu, saya akan menjualnya, terima kasih semua!",
           a8: "Saya mempunyai iPhone saya hari ini. Terima kasih!",
           a9: "Semua hadiah kosong!!!",
           a10: "Terima kasih!",
           a11: "Saya fikir ia adalah gurauan, tetapi iPhone 10 saya tiba pagi ini. Namun, anda mesti mengikut semua arahan dengan berhati-hati..",
           a12: "Saya tidak pernah memenangi apa-apa, tetapi saya bertuah hari ini! Terima kasih!",
           a13: "Saya sesat :(",
           a14: "Saya telah melihat permainan ini tahun lepas tetapi saya tidak mengendahkannya kerana saya fikir ia tidak masuk akal. Kali ini saya mencuba dan saya menang :)",
           a15: "Terima kasih banyak, ini menakjubkan!!!",
           a16: "Sahkan sahaja nombor anda pada halaman seterusnya ;)",
           a17: "Adakah saya seorang sahaja yang tersesat? :( :( :( :(",
           a18: "Terima kasih! Terima kasih!",
           a19: "Itu gurauan?",
           a20: "Anda bertuah!",
           a21: "Anda adalah salah satu daripada 10 orang yang dipilih untuk menyertai loteri kesetiaan kami! Anda boleh mendapat 1 daripada 4 hadiah! Hanya pilih satu kotak.",
           a22: "Maaf, kotak ini kosong! Anda mempunyai lebih banyak percubaan ",
           a23: "Baucar Lazada anda dengan harga Rp500,000 telah ditempah selama lima (5) minit!",
           a24: "Anda akan dialihkan ke apl Lazada rasmi.",
           a25: "Sila pasang untuk menuntut ganjaran anda.",
           montharray: ["Januari", "Februari", "Mac", "April", "Mei", "Jun", "Julai", "Ogos", "September", "Oktober", "November", "Disember"],
           a26: "Jawapan",
           a27: "Suka",
           a28: "minit lalu",
           a29: "jam yang lalu"
    },
    lang['vietnam'] = {
        a1: "Giành giải thưởng từ Lazada!",
            a2: "Để cảm ơn sự trung thành của khách hàng, chúng tôi cung cấp cơ hội nhận được một món quà bí mật!",
            a3: "Tìm một món quà bí mật",
            a4: "Tất cả những gì bạn phải làm là chọn đúng hộp quà",
            a5: "Mọi người thích nó",
            a6: "Có thể chơi lại không? :)",
            a7: "Tôi đã nghe nói về nó! iPhone của tôi vừa được gửi đến trong thư, mặc dù tôi đã có một chiếc, tôi sẽ bán nó, cảm ơn mọi người!",
            a8: "Hôm nay tôi có iPhone. Cảm ơn bạn!",
            a9: "Hết quà rồi !!!",
            a10: "Cảm ơn!",
            a11: "Tôi nghĩ đó là một trò đùa, nhưng iPhone 10 của tôi đã đến vào sáng nay. Tuy nhiên, bạn phải làm theo tất cả các hướng dẫn cẩn thận ..",
            a12: "Tôi chưa bao giờ giành được bất cứ điều gì, nhưng tôi đã gặp may hôm nay! Cảm ơn bạn!",
            a13: "Tôi bị lạc :(",
            a14: "Tôi đã xem trò chơi này năm ngoái nhưng tôi đã bỏ qua nó vì tôi nghĩ nó không có ý nghĩa gì. Lần này tôi đã thử và tôi đã thắng:)",
            a15: "Cảm ơn bạn rất nhiều, điều này thật tuyệt vời !!!",
            a16: "Chỉ cần xác nhận số của bạn trên trang tiếp theo;)",
            a17: "Tôi có phải là người duy nhất bị lạc không? :( :( :( :(",
            a18: "Cảm ơn! Cảm ơn!",
            a19: "Đó là một trò đùa?",
            a20: "Bạn thật may mắn!",
            a21: "Bạn là một trong 10 người được chọn tham gia xổ số dành cho khách hàng thân thiết của chúng tôi! Bạn có thể nhận được 1 trong số 4 giải! Chỉ cần chọn một ô.",
            a22: "Xin lỗi, ô này trống! Bạn còn nhiều lần thử nữa",
            a23: "Phiếu mua hàng Lazada trị giá 500.000 Rp của bạn đã được đặt trước trong năm (5) phút!",
            a24: "Bạn sẽ được chuyển hướng đến ứng dụng Lazada chính thức.",
            a25: "Vui lòng cài đặt nó để nhận phần thưởng của bạn.",
            montharray: ["Tháng 1", "Tháng 2", "Tháng 3", "Tháng 4", "Tháng 5", "Tháng 6", "Tháng 7", "Tháng 8", "Tháng 9", "Tháng 10", "Tháng 11", "Tháng 12"],
            a26: "Trả lời",
            a27: "Thích",
            a28: "phút trước",
            a29: "giờ trước"
    },
    lang['philipins'] = {
       a1: "Manalo ng premyo mula sa Lazada!",
           a2: "Upang pasalamatan ang aming mga customer para sa kanilang katapatan, nag-aalok kami ng pagkakataong makakuha ng isang lihim na regalo!",
           a3: "Maghanap ng lihim na regalo",
           a4: "Ang kailangan mo lang gawin ay piliin ang tamang kahon ng regalo",
           a5: "Gusto ito ng mga tao",
           a6: "Posible bang maglaro ulit? :)",
           a7: "I heard about it! Kakarating lang ng iPhone ko, kahit meron na ako ibebenta ko, salamat sa lahat!",
           a8: "Mayroon akong iPhone ngayon. Salamat!",
           a9: "Lahat ng regalo ay walang laman!!!",
           a10: "Salamat!",
           a11: "Akala ko ito ay isang biro, ngunit ang aking iPhone 10 ay dumating ngayong umaga. Gayunpaman, dapat mong sundin ang lahat ng mga tagubilin nang mabuti..",
           a12: "Wala akong napanalunan, ngunit sinuwerte ako ngayon! Salamat!",
           a13: "Naliligaw ako :(",
           a14: "Nakita ko na ang larong ito noong nakaraang taon ngunit hindi ko ito pinansin dahil akala ko wala itong kabuluhan. Sa pagkakataong ito sinubukan ko at nanalo ako :)",
           a15: "Maraming salamat, ito ay kamangha-manghang!!!",
           a16: "Kumpirmahin lang ang iyong numero sa susunod na pahina ;)",
           a17: "Ako lang ba ang naligaw? :( :( :( :(",
           a18: "Salamat! Salamat!",
           a19: "Joke ba yan?",
           a20: "Ang swerte mo!",
           a21: "Isa ka sa 10 taong napiling lumahok sa aming loyalty lottery! Maaari kang makakuha ng 1 premyo sa 4! Pumili lang ng isang kahon.",
           a22: "Paumanhin, walang laman ang kahon na ito! Marami ka pang pagsubok ",
           a23: "Ang iyong Lazada voucher sa halagang Rp500,000 ay nakareserba sa loob ng limang (5) minuto!",
           a24: "Ire-redirect ka sa opisyal na Lazada app.",
           a25: "Paki-install ito para makuha ang iyong reward.",
           montharray: ["Enero", "Pebrero", "Marso", "Abril", "Mayo", "Hunyo", "Hulyo", "Agosto", "Setyembre", "Oktubre", "Nobyembre", "Disyembre"],
           a26: "Sagot",
           a27: "Tulad",
           a28: "mga minuto ang nakalipas",
           a29: "oras ang nakalipas"
    }